version: '3.7'
services:
  db:
    image: registry.gitlab.com/mbe99/docker-work/mysql:5.7
    container_name: database
    volumes:
     - /tmp/data/mysql:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: top-secret
  web:
    depends_on:
     - db
    image: registry.gitlab.com/mbe99/docker-work/phpmyadmin:latest
    container_name: webserver
    ports:
     - "8082:80"
    restart: always
