version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: prod

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
