version: '3.7'
services:
  db:
    image: mariadb:latest 
    volumes:
     - /tmp/data/mysql:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: top-secret
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress_user
     MYSQL_PASSWORD: 123wordpress

  wp:
    depends_on:
     - db
    image: wordpress:latest
    volumes:
     - /tmp/data/wp/themes:/var/www/html/wp-content/themes/
     - /tmp/data/wp/uploads:/var/www/html/wp-content/uploads/
    ports:
     - "8081:80"
    restart: always
    environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: wordpress_user
     WORDPRESS_DB_PASSWORD: 123wordpress
